[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'tell-k/vim-autopep8'
hook_add = '''
    let g:autopep8_disable_show_diff=1
    let g:autopep8_on_save = 1
'''
on_ft = ['python']
on_i = 1

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']
