[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#virtualenv#enabled = 1
    let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-scripts/fcitx.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    nnoremap <silent> <Leader>w :FixWhitespace<CR>
'''

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <Leader>f :<C-u>NERDTreeToggle<CR>
  let NERDTreeIgnore = ['\.pyc$']
  let g:NERDTreeQuitOnOpen=1
  let g:NERDTreeShowHidden=1
  let g:NERDTreeIgnore=['\.git$', '\.clean$', '\.swp$', '\.bak$', '\~$']
'''

[[plugins]]
repo = "simeji/winresizer"

[[plugins]]
repo = "jacquesbh/vim-showmarks"

[[plugins]]
repo = 'tyru/open-browser.vim'
