[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  " Powerline系フォントを利用する
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#whitespace#mixed_indent_algo = 1
  let g:airline_theme = 'molokai'

  if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif

  " unicode symbols
  let g:airline_left_sep = '»'
  let g:airline_left_sep = '▶'
  let g:airline_right_sep = '«'
  let g:airline_right_sep = '◀'
  let g:airline_symbols.crypt = '🔒'
  let g:airline_symbols.linenr = '␊'
  let g:airline_symbols.linenr = '␤'
  let g:airline_symbols.linenr = '¶'
  let g:airline_symbols.maxlinenr = '☰'
  let g:airline_symbols.maxlinenr = ''
  let g:airline_symbols.branch = '⎇'
  let g:airline_symbols.paste = 'ρ'
  let g:airline_symbols.paste = 'Þ'
  let g:airline_symbols.paste = '∥'
  let g:airline_symbols.spell = 'Ꞩ'
  let g:airline_symbols.notexists = '∄'
  let g:airline_symbols.whitespace = 'Ξ'

  " powerline symbols
  let g:airline_left_sep = ''
  let g:airline_left_alt_sep = ''
  let g:airline_right_sep = ''
  let g:airline_right_alt_sep = ''
  let g:airline_symbols.branch = ''
  let g:airline_symbols.readonly = ''
  let g:airline_symbols.linenr = ''
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-scripts/fcitx.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
  let g:better_whitespace_enabled=1
  let g:strip_whitespace_on_save=1
  let g:strip_whitespace_confirm = 0
  let g:better_whitespace_filetypes_blacklist=['defx', 'diff', 'gitcommit', 'unite', 'qf', 'help']
  nnoremap <silent> <Leader>w :StripWhitespace<CR>
'''

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'
on_idle = 1

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'jacquesbh/vim-showmarks'
hook_add = '''
  nnoremap [Mark] <Nop>
  nmap m [Mark]
  if !exists('g:markrement_char')
      let g:markrement_char = [
      \     'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
      \     'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'
      \ ]
  endif
  nnoremap <silent>[Mark]s :<C-u>call <SID>AutoMarkrement()<CR>:DoShowMarks<CR>
  function! s:AutoMarkrement()
      if !exists('b:markrement_pos')
          let b:markrement_pos = 0
      else
          let b:markrement_pos = (b:markrement_pos + 1) % len(g:markrement_char)
      endif
      execute 'mark' g:markrement_char[b:markrement_pos]
      echo 'marked' g:markrement_char[b:markrement_pos]
  endfunction
  let b:mark_exist = 0
  set updatetime=1
  function! s:MarkList()
    if b:mark_exist == 0
      let b:mark_exist = 1
      nnoremap <silent>[Mark]l :<C-u>1PreviewMarks<CR>
      \:<C-u>NoShowMarks<CR> :<C-u>call <SID>MarkList()<CR>
    else
      let b:mark_exist = 0
      nnoremap <silent>[Mark]l :<C-u>PreviewMarks<CR>
      \:<C-u>DoShowMarks<CR> :<C-u>call <SID>MarkList()<CR>
    endif
  endfunction
  nnoremap <silent>[Mark]l :<C-u>PreviewMarks<CR>
  \:<C-u>DoShowMarks<CR> :<C-u>call <SID>MarkList()<CR>
  nnoremap [Mark]m '
  nnoremap [Mark]n ]`
  nnoremap [Mark]b [`
  nnoremap [Mark]D :<C-u>1PreviewMarks<CR> :delmarks!<CR>
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 1
  let g:EasyMotion_smartcase = 1
  let g:EasyMotion_use_upper = 1
  let g:EasyMotion_enter_jump_first = 1
  let g:EasyMotion_space_jump_first = 1
  nmap <Leader>s <Plug>(easymotion-s2)
  vmap <Leader>s <Plug>(easymotion-s2)
  nmap <Leader>j <Plug>(easymotion-j)
  nmap <Leader>k <Plug>(easymotion-k)
  vmap <Leader>j <Plug>(easymotion-j)
  vmap <Leader>k <Plug>(easymotion-k)
  nmap g/ <Plug>(easymotion-sn)
  vmap g/ <Plug>(easymotion-sn)
  omap g/ <Plug>(easymotion-tn)
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  autocmd ColorScheme * highlight Comment ctermfg=102
  autocmd ColorScheme * highlight Visual ctermbg=239
  colorscheme molokai
'''

